#
# Autogenerated by Thrift Compiler (0.15.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class VectorRecord(object):
    """
    Attributes:
     - key
     - vector
     - attrs
     - file_type
     - file_path
     - root_key
     - chunk_id
     - chunk_text

    """


    def __init__(self, key=None, vector=None, attrs=None, file_type=None, file_path=None, root_key=None, chunk_id=None, chunk_text=None,):
        self.key = key
        self.vector = vector
        self.attrs = attrs
        self.file_type = file_type
        self.file_path = file_path
        self.root_key = root_key
        self.chunk_id = chunk_id
        self.chunk_text = chunk_text

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.key = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.LIST:
                    self.vector = []
                    (_etype3, _size0) = iprot.readListBegin()
                    for _i4 in range(_size0):
                        _elem5 = iprot.readDouble()
                        self.vector.append(_elem5)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.MAP:
                    self.attrs = {}
                    (_ktype7, _vtype8, _size6) = iprot.readMapBegin()
                    for _i10 in range(_size6):
                        _key11 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                        _val12 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                        self.attrs[_key11] = _val12
                    iprot.readMapEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.file_type = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRING:
                    self.file_path = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRING:
                    self.root_key = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.STRING:
                    self.chunk_id = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.STRING:
                    self.chunk_text = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('VectorRecord')
        if self.key is not None:
            oprot.writeFieldBegin('key', TType.STRING, 1)
            oprot.writeString(self.key.encode('utf-8') if sys.version_info[0] == 2 else self.key)
            oprot.writeFieldEnd()
        if self.vector is not None:
            oprot.writeFieldBegin('vector', TType.LIST, 2)
            oprot.writeListBegin(TType.DOUBLE, len(self.vector))
            for iter13 in self.vector:
                oprot.writeDouble(iter13)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.attrs is not None:
            oprot.writeFieldBegin('attrs', TType.MAP, 3)
            oprot.writeMapBegin(TType.STRING, TType.STRING, len(self.attrs))
            for kiter14, viter15 in self.attrs.items():
                oprot.writeString(kiter14.encode('utf-8') if sys.version_info[0] == 2 else kiter14)
                oprot.writeString(viter15.encode('utf-8') if sys.version_info[0] == 2 else viter15)
            oprot.writeMapEnd()
            oprot.writeFieldEnd()
        if self.file_type is not None:
            oprot.writeFieldBegin('file_type', TType.STRING, 4)
            oprot.writeString(self.file_type.encode('utf-8') if sys.version_info[0] == 2 else self.file_type)
            oprot.writeFieldEnd()
        if self.file_path is not None:
            oprot.writeFieldBegin('file_path', TType.STRING, 5)
            oprot.writeString(self.file_path.encode('utf-8') if sys.version_info[0] == 2 else self.file_path)
            oprot.writeFieldEnd()
        if self.root_key is not None:
            oprot.writeFieldBegin('root_key', TType.STRING, 6)
            oprot.writeString(self.root_key.encode('utf-8') if sys.version_info[0] == 2 else self.root_key)
            oprot.writeFieldEnd()
        if self.chunk_id is not None:
            oprot.writeFieldBegin('chunk_id', TType.STRING, 7)
            oprot.writeString(self.chunk_id.encode('utf-8') if sys.version_info[0] == 2 else self.chunk_id)
            oprot.writeFieldEnd()
        if self.chunk_text is not None:
            oprot.writeFieldBegin('chunk_text', TType.STRING, 8)
            oprot.writeString(self.chunk_text.encode('utf-8') if sys.version_info[0] == 2 else self.chunk_text)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.key is None:
            raise TProtocolException(message='Required field key is unset!')
        if self.vector is None:
            raise TProtocolException(message='Required field vector is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class BatchWriteRequest(object):
    """
    Attributes:
     - records
     - replica_num

    """


    def __init__(self, records=None, replica_num=3,):
        self.records = records
        self.replica_num = replica_num

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.LIST:
                    self.records = []
                    (_etype19, _size16) = iprot.readListBegin()
                    for _i20 in range(_size16):
                        _elem21 = VectorRecord()
                        _elem21.read(iprot)
                        self.records.append(_elem21)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.replica_num = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('BatchWriteRequest')
        if self.records is not None:
            oprot.writeFieldBegin('records', TType.LIST, 1)
            oprot.writeListBegin(TType.STRUCT, len(self.records))
            for iter22 in self.records:
                iter22.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.replica_num is not None:
            oprot.writeFieldBegin('replica_num', TType.I32, 2)
            oprot.writeI32(self.replica_num)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.records is None:
            raise TProtocolException(message='Required field records is unset!')
        if self.replica_num is None:
            raise TProtocolException(message='Required field replica_num is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class WriteRequest(object):
    """
    Attributes:
     - record
     - replica_num

    """


    def __init__(self, record=None, replica_num=3,):
        self.record = record
        self.replica_num = replica_num

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.record = VectorRecord()
                    self.record.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.replica_num = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('WriteRequest')
        if self.record is not None:
            oprot.writeFieldBegin('record', TType.STRUCT, 1)
            self.record.write(oprot)
            oprot.writeFieldEnd()
        if self.replica_num is not None:
            oprot.writeFieldBegin('replica_num', TType.I32, 2)
            oprot.writeI32(self.replica_num)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.record is None:
            raise TProtocolException(message='Required field record is unset!')
        if self.replica_num is None:
            raise TProtocolException(message='Required field replica_num is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class DeleteRequest(object):
    """
    Attributes:
     - key

    """


    def __init__(self, key=None,):
        self.key = key

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.key = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('DeleteRequest')
        if self.key is not None:
            oprot.writeFieldBegin('key', TType.STRING, 1)
            oprot.writeString(self.key.encode('utf-8') if sys.version_info[0] == 2 else self.key)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.key is None:
            raise TProtocolException(message='Required field key is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class QueryRequest(object):
    """
    Attributes:
     - vector
     - filter
     - top_k
     - aggregate

    """


    def __init__(self, vector=None, filter=None, top_k=10, aggregate=True,):
        self.vector = vector
        self.filter = filter
        self.top_k = top_k
        self.aggregate = aggregate

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.LIST:
                    self.vector = []
                    (_etype26, _size23) = iprot.readListBegin()
                    for _i27 in range(_size23):
                        _elem28 = iprot.readDouble()
                        self.vector.append(_elem28)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.MAP:
                    self.filter = {}
                    (_ktype30, _vtype31, _size29) = iprot.readMapBegin()
                    for _i33 in range(_size29):
                        _key34 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                        _val35 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                        self.filter[_key34] = _val35
                    iprot.readMapEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.top_k = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.BOOL:
                    self.aggregate = iprot.readBool()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('QueryRequest')
        if self.vector is not None:
            oprot.writeFieldBegin('vector', TType.LIST, 1)
            oprot.writeListBegin(TType.DOUBLE, len(self.vector))
            for iter36 in self.vector:
                oprot.writeDouble(iter36)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.filter is not None:
            oprot.writeFieldBegin('filter', TType.MAP, 2)
            oprot.writeMapBegin(TType.STRING, TType.STRING, len(self.filter))
            for kiter37, viter38 in self.filter.items():
                oprot.writeString(kiter37.encode('utf-8') if sys.version_info[0] == 2 else kiter37)
                oprot.writeString(viter38.encode('utf-8') if sys.version_info[0] == 2 else viter38)
            oprot.writeMapEnd()
            oprot.writeFieldEnd()
        if self.top_k is not None:
            oprot.writeFieldBegin('top_k', TType.I32, 3)
            oprot.writeI32(self.top_k)
            oprot.writeFieldEnd()
        if self.aggregate is not None:
            oprot.writeFieldBegin('aggregate', TType.BOOL, 4)
            oprot.writeBool(self.aggregate)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class QueryResponse(object):
    """
    Attributes:
     - records
     - code
     - msg
     - aggregated_records

    """


    def __init__(self, records=None, code=0, msg="success", aggregated_records=None,):
        self.records = records
        self.code = code
        self.msg = msg
        self.aggregated_records = aggregated_records

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.LIST:
                    self.records = []
                    (_etype42, _size39) = iprot.readListBegin()
                    for _i43 in range(_size39):
                        _elem44 = VectorRecord()
                        _elem44.read(iprot)
                        self.records.append(_elem44)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.code = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.msg = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.MAP:
                    self.aggregated_records = {}
                    (_ktype46, _vtype47, _size45) = iprot.readMapBegin()
                    for _i49 in range(_size45):
                        _key50 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                        _val51 = []
                        (_etype55, _size52) = iprot.readListBegin()
                        for _i56 in range(_size52):
                            _elem57 = VectorRecord()
                            _elem57.read(iprot)
                            _val51.append(_elem57)
                        iprot.readListEnd()
                        self.aggregated_records[_key50] = _val51
                    iprot.readMapEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('QueryResponse')
        if self.records is not None:
            oprot.writeFieldBegin('records', TType.LIST, 1)
            oprot.writeListBegin(TType.STRUCT, len(self.records))
            for iter58 in self.records:
                iter58.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.code is not None:
            oprot.writeFieldBegin('code', TType.I32, 2)
            oprot.writeI32(self.code)
            oprot.writeFieldEnd()
        if self.msg is not None:
            oprot.writeFieldBegin('msg', TType.STRING, 3)
            oprot.writeString(self.msg.encode('utf-8') if sys.version_info[0] == 2 else self.msg)
            oprot.writeFieldEnd()
        if self.aggregated_records is not None:
            oprot.writeFieldBegin('aggregated_records', TType.MAP, 4)
            oprot.writeMapBegin(TType.STRING, TType.LIST, len(self.aggregated_records))
            for kiter59, viter60 in self.aggregated_records.items():
                oprot.writeString(kiter59.encode('utf-8') if sys.version_info[0] == 2 else kiter59)
                oprot.writeListBegin(TType.STRUCT, len(viter60))
                for iter61 in viter60:
                    iter61.write(oprot)
                oprot.writeListEnd()
            oprot.writeMapEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.records is None:
            raise TProtocolException(message='Required field records is unset!')
        if self.code is None:
            raise TProtocolException(message='Required field code is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class BaseResponse(object):
    """
    Attributes:
     - code
     - msg

    """


    def __init__(self, code=0, msg="success",):
        self.code = code
        self.msg = msg

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.code = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.msg = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('BaseResponse')
        if self.code is not None:
            oprot.writeFieldBegin('code', TType.I32, 1)
            oprot.writeI32(self.code)
            oprot.writeFieldEnd()
        if self.msg is not None:
            oprot.writeFieldBegin('msg', TType.STRING, 2)
            oprot.writeString(self.msg.encode('utf-8') if sys.version_info[0] == 2 else self.msg)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.code is None:
            raise TProtocolException(message='Required field code is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(VectorRecord)
VectorRecord.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'key', 'UTF8', None, ),  # 1
    (2, TType.LIST, 'vector', (TType.DOUBLE, None, False), None, ),  # 2
    (3, TType.MAP, 'attrs', (TType.STRING, 'UTF8', TType.STRING, 'UTF8', False), None, ),  # 3
    (4, TType.STRING, 'file_type', 'UTF8', None, ),  # 4
    (5, TType.STRING, 'file_path', 'UTF8', None, ),  # 5
    (6, TType.STRING, 'root_key', 'UTF8', None, ),  # 6
    (7, TType.STRING, 'chunk_id', 'UTF8', None, ),  # 7
    (8, TType.STRING, 'chunk_text', 'UTF8', None, ),  # 8
)
all_structs.append(BatchWriteRequest)
BatchWriteRequest.thrift_spec = (
    None,  # 0
    (1, TType.LIST, 'records', (TType.STRUCT, [VectorRecord, None], False), None, ),  # 1
    (2, TType.I32, 'replica_num', None, 3, ),  # 2
)
all_structs.append(WriteRequest)
WriteRequest.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'record', [VectorRecord, None], None, ),  # 1
    (2, TType.I32, 'replica_num', None, 3, ),  # 2
)
all_structs.append(DeleteRequest)
DeleteRequest.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'key', 'UTF8', None, ),  # 1
)
all_structs.append(QueryRequest)
QueryRequest.thrift_spec = (
    None,  # 0
    (1, TType.LIST, 'vector', (TType.DOUBLE, None, False), None, ),  # 1
    (2, TType.MAP, 'filter', (TType.STRING, 'UTF8', TType.STRING, 'UTF8', False), None, ),  # 2
    (3, TType.I32, 'top_k', None, 10, ),  # 3
    (4, TType.BOOL, 'aggregate', None, True, ),  # 4
)
all_structs.append(QueryResponse)
QueryResponse.thrift_spec = (
    None,  # 0
    (1, TType.LIST, 'records', (TType.STRUCT, [VectorRecord, None], False), None, ),  # 1
    (2, TType.I32, 'code', None, 0, ),  # 2
    (3, TType.STRING, 'msg', 'UTF8', "success", ),  # 3
    (4, TType.MAP, 'aggregated_records', (TType.STRING, 'UTF8', TType.LIST, (TType.STRUCT, [VectorRecord, None], False), False), None, ),  # 4
)
all_structs.append(BaseResponse)
BaseResponse.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'code', None, 0, ),  # 1
    (2, TType.STRING, 'msg', 'UTF8', "success", ),  # 2
)
fix_spec(all_structs)
del all_structs
