# RPC基础配置
COORDINATOR_DEFAULT_PORT = 8081
DATANODE_DEFAULT_PORT_START = 9090
RPC_BUFFER_SIZE = 4096
RPC_TIMEOUT = 5000  # RPC调用超时（ms）

# RPC连接池配置
RPC_POOL_SIZE = 10  # 每个数据节点最大连接数
RPC_POOL_IDLE_TIMEOUT = 30  # 空闲连接超时（s）